---
abstract: 'Yet another scraping library like jQuery'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Cwd: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test2::Tools::Exception: '0'
  Test2::V0: '0'
  Test::Exception: '0'
  Test::More: '0'
  lib: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Web-Query
provides:
  Web::Query:
    file: lib/Web/Query.pm
    version: '1.00'
  Web::Query::LibXML:
    file: lib/Web/Query/LibXML.pm
    version: '1.00'
requires:
  Exporter: '0'
  HTML::Entities: '0'
  HTML::Selector::XPath: '0.20'
  HTML::TreeBuilder::LibXML: '0'
  HTML::TreeBuilder::XPath: '0'
  LWP::UserAgent: '0'
  List::Util: '1.44'
  Scalar::Util: '0'
  parent: '0'
  perl: '5.008005'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/tokuhirom/Web-Query/issues
  homepage: https://github.com/tokuhirom/Web-Query
  repository: https://github.com/tokuhirom/Web-Query.git
version: '1.00'
x_authority: cpan:TOKUHIROM
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Carlos Fernando Avila Gratz <cafe01@gmail.com>'
  - 'DQNEO <dqneoo@gmail.com>'
  - 'Hiroki Honda <cside.story@gmail.com>'
  - 'Kang-min Liu <gugod@gugod.org>'
  - 'Maurice Aubrey <maurice.aubrey@gmail.com>'
  - 'moznion <moznion@gmail.com>'
  - 'Oleg <verdrehung@gmail.com>'
  - 'Tokuhiro Matsuno <tokuhirom+cpan@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
  - 'Yanick Champoux <yanick@cpan.org>'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
